import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// On GitHub Actions, serve under /<repo>/ (project page). Locally & on Vercel, '/'.
const repo = process.env.GITHUB_REPOSITORY?.split('/')[1]
const base = process.env.GITHUB_ACTIONS && repo ? `/${repo}/` : '/'

/* Installing to a home screen.

   An inspector works on a phone, often with the unit in front of them and
   the browser chrome eating a fifth of the screen. Installed, the app gets
   the whole screen and its own icon in the launcher, and — because the
   service worker holds the shell — it opens on a site with no signal,
   which is the ordinary case in a yard or a workshop.

   Manifest and worker are emitted here rather than kept as static files
   because both have to carry the base path, and that path is only known
   at build time: '/' locally, '/DocumentControlQC/' on Pages. A manifest
   with the wrong scope installs an app that opens a 404. */
const BUILD = new Date().toISOString()

const manifest = {
  id: `${base}?app`,
  name: 'QC Inspection Monitor',
  short_name: 'QC Monitor',
  description: 'QA/QC field inspection forms, report monitoring and data books.',
  start_url: `${base}?app`,
  scope: base,
  // standalone, not fullscreen: it takes the browser's chrome away but
  // leaves the clock and the battery, which somebody timing a 30-minute
  // hold has a use for.
  display: 'standalone',
  background_color: '#ffffff',
  theme_color: '#ffffff',
  icons: [
    { src: `${base}icon-192.png`, sizes: '192x192', type: 'image/png' },
    { src: `${base}icon-512.png`, sizes: '512x512', type: 'image/png' },
    { src: `${base}icon-maskable-512.png`, sizes: '512x512', type: 'image/png', purpose: 'maskable' },
  ],
}

/* The worker.

   Navigations go to the network first and fall back to the cache. That
   ordering matters here: a cache-first shell is how an app gets stuck on
   a build from last week, and this one has already had a stale-data
   problem once. Hashed assets are immutable by construction, so those are
   served from the cache and only fetched once.

   The cache is named for the build, and activate deletes every other one,
   so a deploy cannot leave the previous version's files behind. */
const sw = `/* generated by vite.config.js — do not edit */
const VERSION = ${JSON.stringify(BUILD)}
const CACHE = 'qc-' + VERSION
const BASE = ${JSON.stringify(base)}
const SHELL = [BASE, BASE + 'index.html', BASE + 'icon-192.png', BASE + 'icon-512.png']

self.addEventListener('install', (e) => {
  e.waitUntil((async () => {
    const c = await caches.open(CACHE)
    // One missing file must not fail the whole install.
    await Promise.allSettled(SHELL.map((u) => c.add(new Request(u, { cache: 'reload' }))))
    self.skipWaiting()
  })())
})

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    for (const k of await caches.keys()) if (k !== CACHE) await caches.delete(k)
    await self.clients.claim()
  })())
})

self.addEventListener('fetch', (e) => {
  const req = e.request
  if (req.method !== 'GET') return
  const url = new URL(req.url)
  if (url.origin !== self.location.origin) return

  // A page load: newest wins, cache is the fallback when there is no signal.
  if (req.mode === 'navigate') {
    e.respondWith((async () => {
      try {
        const fresh = await fetch(req)
        const c = await caches.open(CACHE)
        c.put(BASE + 'index.html', fresh.clone())
        return fresh
      } catch {
        return (await caches.match(BASE + 'index.html')) || Response.error()
      }
    })())
    return
  }

  // Everything else is content-hashed, so once it is here it is final.
  e.respondWith((async () => {
    const hit = await caches.match(req)
    if (hit) return hit
    const res = await fetch(req)
    if (res.ok && res.type === 'basic') (await caches.open(CACHE)).put(req, res.clone())
    return res
  })())
})
`

const pwa = () => ({
  name: 'qc-pwa',
  transformIndexHtml(html) {
    return html.replace('</head>', `  <link rel="manifest" href="${base}manifest.webmanifest" />
    <link rel="apple-touch-icon" href="${base}apple-touch-icon.png" />
    <meta name="application-name" content="QC Inspection Monitor" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-title" content="QC Monitor" />
    <!-- iOS paints the notch area with this; black-translucent lets the
         page's own background run under the status bar in both themes. -->
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
    <meta name="mobile-web-app-capable" content="yes" />
    <!-- Two, so the Android status bar follows the phone's theme rather
         than being one colour that is wrong half the time. theme.js
         rewrites them when the in-app choice is not "system". -->
    <meta name="theme-color" media="(prefers-color-scheme: light)" content="#ffffff" />
    <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#0f0f12" />
  </head>`)
  },
  generateBundle() {
    this.emitFile({ type: 'asset', fileName: 'manifest.webmanifest', source: JSON.stringify(manifest, null, 2) })
    this.emitFile({ type: 'asset', fileName: 'sw.js', source: sw })
  },
})

export default defineConfig({
  base,
  plugins: [react(), pwa()],
  server: { port: 5173, open: false },
})
